In [13]:
# 切换工作目录，主要适用于google colab中的开发
import os

if "第三题.ipynb" not in os.listdir():
  try:
    os.chdir("drive/MyDrive")
    os.chdir("NN_Homework")
    os.chdir("HW4")
  except:
    print("无法找到正确工作目录！")

assert "第三题.ipynb" in os.listdir()

In [14]:
# 生成数据集
import numpy as np
import torch.utils.data as Data

x_train = np.linspace(-np.pi, np.pi, 100).reshape(-1,1)
y_train = np.sin(x_train)

print(x_train.shape,y_train.shape)

# 生成pytorch数据集
y_train = torch.from_numpy(y_train).float()
x_train = torch.from_numpy(x_train).float()
train_set = Data.TensorDataset(x_train, y_train)
train_iter = Data.DataLoader(train_set, batch_size=20, shuffle=True)

(100, 1) (100, 1)


In [15]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # 设定设备
import torch.nn as nn
import torch.nn.functional as F

# 固定随机种子
def set_random_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ['PYTHONHASHSEED'] = str(seed)
set_random_seed(2020)


class MLP(nn.Module):
  def __init__(self, in_dim, hidden_dim):
    super(MLP, self).__init__()
    self.linear1 = nn.Linear(in_dim, hidden_dim)
    self.linear2 = nn.Linear(hidden_dim, 1)
  
  def forward(self, x):
    x = self.linear1(x)
    x = F.relu(x)
    x = self.linear2(x)
    return x
  
  def out_by_layer(self, x):
    x = self.linear1(x)
    x = F.relu(x)
    print(x)
    x = self.linear2(x)
    print(x)


#instantiate model
mlp = MLP(1, 5).to(device)
mse = nn.MSELoss()
optimizer = torch.optim.Adam(mlp.parameters())

for epoch in range(100):
  train_l_sum, train_acc_sum, n = 0.0, 0.0, 0
  for x, y in train_iter:
    y_pred = mlp(x)
    loss = mse(y_pred,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    train_l_sum += loss.item()
    n += y.shape[0]
  print('epoch %d, loss %.4f'%(epoch + 1, train_l_sum / n))

epoch 1, loss 0.0457
epoch 2, loss 0.0438
epoch 3, loss 0.0423
epoch 4, loss 0.0407
epoch 5, loss 0.0391
epoch 6, loss 0.0377
epoch 7, loss 0.0364
epoch 8, loss 0.0352
epoch 9, loss 0.0340
epoch 10, loss 0.0328
epoch 11, loss 0.0316
epoch 12, loss 0.0306
epoch 13, loss 0.0296
epoch 14, loss 0.0287
epoch 15, loss 0.0277
epoch 16, loss 0.0268
epoch 17, loss 0.0259
epoch 18, loss 0.0251
epoch 19, loss 0.0243
epoch 20, loss 0.0236
epoch 21, loss 0.0229
epoch 22, loss 0.0222
epoch 23, loss 0.0216
epoch 24, loss 0.0209
epoch 25, loss 0.0203
epoch 26, loss 0.0197
epoch 27, loss 0.0191
epoch 28, loss 0.0186
epoch 29, loss 0.0181
epoch 30, loss 0.0176
epoch 31, loss 0.0171
epoch 32, loss 0.0166
epoch 33, loss 0.0162
epoch 34, loss 0.0157
epoch 35, loss 0.0153
epoch 36, loss 0.0149
epoch 37, loss 0.0146
epoch 38, loss 0.0142
epoch 39, loss 0.0139
epoch 40, loss 0.0135
epoch 41, loss 0.0132
epoch 42, loss 0.0129
epoch 43, loss 0.0126
epoch 44, loss 0.0124
epoch 45, loss 0.0121
epoch 46, loss 0.01

In [16]:
for name, param in mlp.named_parameters():
  print(name,param)
mlp.out_by_layer(x_train)

linear1.weight Parameter containing:
tensor([[-0.0263],
        [-0.6343],
        [ 0.4072],
        [-1.1352],
        [ 0.1665]], requires_grad=True)
linear1.bias Parameter containing:
tensor([-0.4353, -0.0133,  0.4695,  0.0069,  0.1663], requires_grad=True)
linear2.weight Parameter containing:
tensor([[ 0.0360,  0.0840,  0.4442, -0.2487,  0.4166]], requires_grad=True)
linear2.bias Parameter containing:
tensor([-0.1576], requires_grad=True)
tensor([[0.0000e+00, 1.9793e+00, 0.0000e+00, 3.5733e+00, 0.0000e+00],
        [0.0000e+00, 1.9391e+00, 0.0000e+00, 3.5013e+00, 0.0000e+00],
        [0.0000e+00, 1.8988e+00, 0.0000e+00, 3.4292e+00, 0.0000e+00],
        [0.0000e+00, 1.8585e+00, 0.0000e+00, 3.3572e+00, 0.0000e+00],
        [0.0000e+00, 1.8183e+00, 0.0000e+00, 3.2851e+00, 0.0000e+00],
        [0.0000e+00, 1.7780e+00, 0.0000e+00, 3.2131e+00, 0.0000e+00],
        [0.0000e+00, 1.7378e+00, 0.0000e+00, 3.1410e+00, 0.0000e+00],
        [0.0000e+00, 1.6975e+00, 0.0000e+00, 3.0690e+00, 0.000